### GET INFO
GET http://localhost:3001/info

### GET ALL RENDER
GET https://render-test-dkba.onrender.com/api/persons

### GET ALL
GET http://localhost:3001/api/persons

### GET ID
GET http://localhost:3001/api/persons/654a18d5c5a5e98e93b9ea64

### DELETE ID
DELETE http://localhost:3001/api/persons/654a3781d54d93b31f189c47

### ADD PERSON
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "PAUKKU PATE",
    "number": "12-34-5678902",
} 
### ADD ERROR
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "name",
    "number": ""
} 

### UNKNOWN END POINT
GET http://localhost:3001/LOLOLOLO
