### GET INFO
GET http://localhost:3001/info

### GET ALL RENDER
GET https://render-test-dkba.onrender.com/api/persons

### GET ALL
GET http://localhost:3001/api/persons

### GET ID
GET http://localhost:3001/api/persons/2

### DELETE ID
DELETE http://localhost:3001/api/persons/2

### ADD PERSON
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "PAUKKU PATE",
    "number": "12-34-567890"
} 
### ADD ERROR
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "name",
    "number": ""
} 

### UNKNOWN END POINT
GET http://localhost:3001/LOLOLOLO
